namespace Flowbite.Components.Chat;

/// <summary>
/// Represents the message author role within a chat conversation.
/// </summary>
public enum ChatMessageRole
{
    /// <summary>
    /// A message authored by the end user.
    /// </summary>
    User,

    /// <summary>
    /// A message generated by the assistant / model.
    /// </summary>
    Assistant,

    /// <summary>
    /// System level message such as instructions.
    /// </summary>
    System
}
